// <auto-generated />
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace QuizWhois.Domain.Migrations
{
    public partial class ChangeQuizToPackMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "Quizzes",
                newName: "Packs");

            migrationBuilder.RenameColumn(
                name: "QuizId",
                table: "Question",
                newName: "PackId");

            migrationBuilder.AddColumn<string>(
                name: "Description",
                table: "Packs",
                type: "longtext",
                nullable: true).Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.AddColumn<bool>(
                name: "IsDraft",
                table: "Packs",
                type: "tinyint(1)",
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "Packs",
                newName: "Quizzes");

            migrationBuilder.RenameColumn(
                name: "PackId",
                table: "Question",
                newName: "QuizId");

            migrationBuilder.DropColumn(
                name: "Description",
                table: "Quizzes");
        }
    }
}
